[package]
name = "jcc"
version = "0.1.0"
authors = ["Uku Taht <uku.taht@gmail.com>"]

[lib]
doctest = false
doc = false

[[test]]
name = "suite"
harness = false

[dependencies]
serde_json = "1.0"

[dev-dependencies]
rustc-test = "0.1"
glob = "0.2"
